-- =============================================================================
-- XLeats — offer matching job
--
-- Superseded: this used to be a birthday-only matcher (generate_birthday_offers).
-- It's now generalized as generate_scheduled_offers(), defined in schema.sql
-- alongside offers/offer_redemptions (birthday_offers/birthday_redemptions
-- were renamed there too). Keeping this file only as the historical "run
-- this after schema.sql" pointer — the actual function lives in schema.sql
-- since it was already the single source of truth for every other function.
--
-- Call generate_scheduled_offers() once per morning from the /api/cron/offers
-- Vercel cron. It runs as the platform, writes a per-customer redemption
-- code, and NEVER exposes customer rows to trucks — they only ever see
-- counts via offer_stats(). new_follower offers don't go through this job at
-- all — they fire immediately via the on_new_follow trigger on `follows`.
-- =============================================================================
